[package]
name = "todo"
version = "4.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
todo-lib = {git = "https://github.com/kyllingene/todo-lib"}
sarge = "4.0.2"
dirs = "5.0.1"
errata = "1.1.1"
